from log_into_wiki import *
import mwparserfromhell

site = login('me', 'blacksurvival')  # Set wiki
summary = 'Recipes into infobox'  # Set summary

limit = -1
# startat_page = 'asdf'
this_template = site.pages['Module:RecipeDatabase']  # Set template
pages = this_template.embeddedin()

pages_var = list(pages)

pages_array = [p.name for p in pages_var]

try:
	startat = pages_array.index(startat_page)
except NameError as e:
	startat = -1
except ValueError as e:
	startat = -1
print(startat)



recipes = {
"Tachyon Blade" :  ["Engineered Arcane Motor", "Laser Pointer"],
"Laser Pointer" :  [],
"Engineered Arcane Motor" :  ["Motor", "Arcane Stone"],
"Motor" : ["Steel", "Electronic Parts"],
"Electronic Parts" :  ["Wire", "Battery"],
"Wire" : [],
"Battery" : [],
"Steel" : ["Iron Ore", "Scrap Metal"],
"Iron Ore" :  [],
"Scrap Metal" :  [],
"Arcane Stone" :  ["Flint", "Holy Blood"],
"Holy Blood" :  [],
"Flint" : ["Stone", "Gunpowder"],
"Stone" : [],
"Gunpowder" : [],
"Arcane Edge" :  ["Arcane Stone", "Bastard Sword"],
"Jamadhar" : ["Kitchen Knife", "Knuckle"],
"Kitchen Knife" :  [],
"Knuckle" : [],
"Laevateinn" : ["True Samadhi Fire", "Jewel Sword"],
"True Samadhi Fire" :  ["Powder of Life", "Lighter"],
"Lighter" : [],
"Powder of Life" :  ["Tree of Life", "Stone"],
"Tree of Life" :  [],
"Jewel Sword" :  ["Knife", "Ruby"],
"Knife" : [],
"Ruby" : ["Gemstone", "Hammer"],
"Gemstone" : [],
"Hammer" : [],
"Axe of Pangu" :  ["Battle Axe", "Adamantium"],
"Battle Axe" :  ["Spear Handle", "Hatchet"],
"Spear Handle" :  [],
"Hatchet" : [],
"Adamantium" : ["Mithril", "Iron Ore"],
"Mithril" : [],
"Sky Piercer" :  ["Halberd Axe", "Horse Guandao"],
"Halberd Axe" :  ["Long Spear", "Hatchet"],
"Long Spear" :  ["Short Spear", "Spear Handle"],
"Short Spear" :  [],
"Horse Guandao" :  ["Spear Handle", "Scimitar"],
"Scimitar" : ["Shamshir", "Kitchen Knife"],
"Shamshir" : [],
"Dáinsleif" :  ["Holy Blood", "Bastard Sword"],
"Bastard Sword" :  ["Long Sword", "Steel"],
"Long Sword" :  [],
"Dragon Guandao" :  ["Halberd Axe", "Tree of Life"],
"Beam Axe" :  ["Battle Axe", "Plasma Sword"],
"Plasma Sword" :  ["Laser Pointer", "Sabre"],
"Sabre" :  ["Shamshir", "Heated Whetstone"],
"Heated Whetstone" :  ["Whetstone", "Lighter"],
"Lighter" : [],
"Whetstone" : [],
"Santa Muerte" :  ["Reaper's Scythe", "Horse Guandao"],
"Reaper's Scythe" :  ["Sickle", "Spear Handle"],
"Sickle" : [],
"Hades' Edge" :  ["Bastard Sword", "Rapier"],
"Rapier" : ["Sabre", "Heated Whetstone"],
"Seven Star Sword" :  ["Meteorite", "Jewel Sword"],
"Meteorite" : [],
"Vibroblade" : ["Motor", "Knife"],
"Hǫfuð" :  ["Jewel Sword", "Glass Pieces"],
"Glass Pieces" :  ["Stone", "Glass Cup"],
"Glass Cup" :  [],
"Harpe" : ["Scimitar", "Jewel Sword"],
"Divine Dual Swords" :  ["Muramasa", "Masamune"],
"Muramasa" : [],
"Masamune" : [],
"Monohoshizao" : ["Odachi", "Blueprint"],
"Odachi" : ["Katana", "Iron Sheet"],
"Katana" : [],
"Iron Sheet" :  ["Scrap Metal", "Hammer"],
"Blueprint" : ["Fountain Pen", "Thick Paper"],
"Fountain Pen" :  [],
"Thick Paper" :  [],
"Durendal mk2" :  ["Plasma Sword", "Tree of Life"],
"Meteor Claymore" :  ["Meteorsteel", "Long Sword"],
"Meteorsteel" : ["Meteorite", "Iron Ore"],
"Starsteel Twin Sword" :  ["Meteorsteel", "Twin Sword"],
"Twin Sword" :  ["Kitchen Knife", "Sharp Kitchen Knife"],
"Sharp Kitchen Knife" :  ["Kitchen Knife", "Whetstone"],
"Excalibur" : ["Jewel Sword", "Cross"],
"Cross" : [],
"Chainsaw" : ["Soldering Iron", "Battery"],
"Soldering Iron" :  ["Nail", "Electronic Parts"],
"Nail" : [],
"Arondight" : ["Bastard Sword", "Cross"],
"Sword of Justice" :  ["Stallion Medal", "Long Sword"],
"Stallion Medal" :  [],
"Army Knife" :  ["Knife", "Branch"],
"Branch" : [],
"Axe Chain" :  ["Steel Chain", "Hatchet"],
"Steel Chain" :  [],
"Chain Scythe" :  ["Steel Chain", "Sickle"],
"Pickaxe" : [],
"Crude Axe" :  [],
"Scissors" : [],
"Razor" : [],
"Box Cutter" :  [],
"Blazing Lance" :  ["Long Spear", "True Samadhi Fire"],
"Spear of Longinus" :  ["Long Spear", "Holy Blood"],
"Lance of Poseidon" :  ["Trident", "Purified Water"],
"Trident" : ["Twin Sword", "Long Spear"],
"Purified Water" :  ["Boiling Water", "Ice"],
"Ice" : [],
"Boiling Water" :  ["Water", "Lighter"],
"Lighter" : [],
"Water" : [],
"Cosmic Bident" :  ["Bident", "Ion Battery"],
"Ion Battery" :  ["Sports Drink", "Battery"],
"Sports Drink" :  [],
"Bident" : ["Rapier", "Short Spear"],
"Vijayanagara" : ["Volticletto", "Hooded Katar"],
"Volticletto" :  ["Awl", "Electronic Parts"],
"Awl" : ["Nail", "Scrap Metal"],
"Hooded Katar" :  ["Arm Warmers", "Jamadhar"],
"Arm Warmers" :  [],
"Pile Bunker" :  ["SGOTY870", "Harpoon"],
"SGOTY870" :  [],
"Harpoon" : [],
"Bamboo Spear" :  ["Bamboo", "Knife"],
"Bamboo" : [],
"Crude Awl" :  [],
"Needle" : [],
"Monkey King Bar" :  ["Engineered Arcane Motor", "Long Rod"],
"Long Rod" :  [],
"Magic Stick" :  ["Warhammer", "Moonlight Pendant"],
"Warhammer" : ["Hammer", "Spear Handle"],
"Moonlight Pendant" :  ["Moon Stone", "Ribbon"],
"Ribbon" : [],
"Moon Stone" :  ["Meteorsteel", "Stone"],
"Statue of Soteria" :  ["Torch", "Anatomy Model"],
"Anatomy Model" :  [],
"Torch" : ["Torch Hold", "Lighter"],
"Torch Hold" :  ["Bamboo", "Oilcloth"],
"Oilcloth" :  ["Cloth", "Oil"],
"Oil" : [],
"Cloth" : [],
"Gleipnir" : ["Rope Cuffs", "Thorn Whip"],
"Rope Cuffs" :  ["Stallion Medal", "Whip"],
"Whip" : [],
"Thorn Whip" :  ["Whip", "Spiked Plank"],
"Spiked Plank" :  ["Needle", "Branch"],
"Fang Mace" :  ["Arcane Stone", "Goblin Bat"],
"Goblin Bat" :  ["Nail", "Short Rod"],
"Short Rod" :  [],
"Hammer of Thor" :  ["Dwarf's Mallet", "High Voltage Line"],
"Dwarf's Mallet" :  ["Warhammer", "Adamantium"],
"High Voltage Line" :  ["Wire", "Dead Battery"],
"Dead Battery" :  ["Battery", "Water"],
"Plasma Whip" :  ["Lightning Whip", "Electric Whip"],
"Lightning Whip" :  ["Bullwhip", "Dead Battery"],
"Bullwhip" : ["Razor", "Whip"],
"Electric Whip" :  ["Whip", "High Voltage Line"],
"Banana Leaf Fan" :  ["White Crane Fan", "Umbrella"],
"White Crane Fan" :  ["Fan", "Feather"],
"Fan" : [],
"Feather" : [],
"Titan Hammer" :  ["Warhammer", "Ogre Skin"],
"Ogre Skin" :  [],
"Red Muffler" :  ["Scarf", "Holy Blood"],
"Scarf" : [],
"Vajra" : ["Tree of Life", "Spiked Bat"],
"Spiked Bat" :  ["Bat (weapon)", "Nail"],
"Bat (weapon)" :  [],
"Plasma Tonfa" :  ["Steel Tonfa", "Laser Pointer"],
"Steel Tonfa" :  ["Tonfa", "Steel"],
"Tonfa" : ["Short Rod", "Cotton Work Glove"],
"Cotton Work Glove" :  [],
"Spy Umbrella" :  ["Umbrella", "Poison"],
"Umbrella" : ["Oilcloth", "Long Rod"],
"Poison" : ["Fertilizer", "Lye"],
"Fertilizer" : [],
"Lye" : ["Water", "Ash"],
"Ash" : ["Thick Paper", "Lighter"],
"Double Nunchaku" :  ["Nunchaku", "Bullwhip"],
"Nunchaku" : ["Chain Rod", "Short Rod"],
"Chain Rod" :  ["Steel Chain", "Short Rod"],
"Triple Nunchaku" :  ["Nunchaku", "Chain Rod"],
"Thunder Whip" :  ["Bullwhip", "Gold"],
"Gold" :  ["Pickaxe", "Gemstone"],
"Flail" : ["Chain Rod", "Iron Ball"],
"Iron Ball" :  [],
"Golf Club" :  ["Heated Steel Pipe", "Hammer"],
"Heated Steel Pipe" :  ["Steel Pipe", "Lighter"],
"Steel Pipe" :  [],
"Iron Mace" :  ["Stone Axe", "Steel Chain"],
"Stone Axe" :  ["Stone", "Bamboo"],
"Claw Hammer" :  [],
"Leather Whip" :  ["Scissors", "Leather"],
"Leather" : [],
"Nightstick" : [],
"Heated Frying Pan" :  ["Frying Pan", "Lighter"],
"Frying Pan" :  [],
"Morning Star" :  ["Long Rod", "Iron Ball"],
"Feather Duster" :  ["Feather", "Spear Handle"],
"Flag Pole" :  ["Long Rod", "Nail"],
"Wooden Fish" :  [],
"Crude Bat" :  [],
"Scrolls of DongYi" :  [],
"Ripped Scroll - 2" :  [],
"Ripped Scroll - 1" :  [],
"Buddhist Scripture" :  [],
"Dart of Blood" :  ["Dart of Souls", "Stingburst"],
"Dart of Souls" :  ["Venom Dart", "Glacial Ice"],
"Glacial Ice" :  ["Powder of Life", "Ice"],
"Venom Dart" :  ["Needle", "Poison"],
"Stingburst" : ["RDX", "Spiked Plank"],
"RDX" : ["Scrap Metal", "Dynamite"],
"Dynamite" : ["Gunpowder", "Wire"],
"Sudarsana" : ["Engineered Arcane Motor", "CD"],
"CD" : [],
"Bone Crusher" :  ["Tomahawk", "Motor"],
"Tomahawk" : ["Hatchet", "Leather"],
"High Explosive Grenade" :  ["Grenade", "Mine"],
"Grenade" : ["Gunpowder", "Iron Ball"],
"Mine" : ["RDX", "Enhanced Mouse Trap"],
"Enhanced Mouse Trap" :  ["Mouse Trap", "Glue"],
"Glue" : [],
"Mouse Trap" :  [],
"David's Sling" :  ["Adamantium", "Arcane Stone"],
"Fuhma Shuriken" :  ["Throwing Stars", "Twin Sword"],
"Throwing Stars" :  ["Box Cutter", "Razor"],
"Azure Dagger" :  ["Onyx Dagger", "Poison"],
"Onyx Dagger" :  ["Throwing Dagger", "Cross"],
"Throwing Dagger" :  [],
"Astrape" : ["Pilum", "Volticletto"],
"Pilum" : ["Javelin", "Short Spear"],
"Javelin" : ["Throwing Dagger", "Spear Handle"],
"Bloody Chakram" :  ["Chakram", "Holy Blood"],
"Chakram" : ["Throwing Stars", "CD"],
"Ruthenium Marble" :  ["Spiky Bouncy Ball", "Gold"],
"Spiky Bouncy Ball" :  ["Glass Pieces", "Flubber"],
"Flubber" :  ["Rubber", "Boiling Water"],
"Rubber" : [],
"Dharma Chakram" :  ["Buddhist Scripture", "Chakram"],
"Incendiary Bomb" :  ["Molotov Cocktail", "Gunpowder"],
"Molotov Cocktail" :  ["Oil", "Glass Bottle"],
"Glass Bottle" :  [],
"Enhanced Boomerang" :  ["Boomerang", "Oilcloth"],
"Boomerang" : ["Branch", "Rubber"],
"Trick Card" :  ["Buddhist Scripture", "Playing Cards"],
"Playing Cards" :  [],
"Storm Bolt" :  ["Warhammer", "Dead Battery"],
"Flour Bomb" :  ["White Powder", "Plastic Bottle"],
"White Powder" :  ["White Chalk", "Stone"],
"White Chalk" :  [],
"Plastic Bottle" :  [],
"Vintage Card" :  ["Playing Cards", "Fountain Pen"],
"TV" : [],
"Heated Oil" :  ["Lighter", "Oil"],
"Dart" : [],
"Shuriken" : [],
"Glue Lump" :  ["Glue", "Boiling Water"],
"Paper Ball" :  ["Thick Paper", "Glue"],
"CD Player" :  ["Electronic Parts", "Glass Marble"],
"Glass Marble" :  [],
"Laptop (broken screen)" :  [],
"Cooking Pot" :  [],
"Holy Grail" :  [],
"Baseball Set" :  [],
"Crude Ball" :  [],
"Mudfish" : [],
"Carp" : [],
"Can" : [],
"Dice" : [],
"Plate" : [],
"Kelte" : ["Engineered Arcane Motor", "Magnum-Python"],
"Magnum-Python" :  [],
"Grand Hand Cannon" :  ["Hand Cannon", "True Samadhi Fire"],
"Hand Cannon" :  ["Iron Sheet", "Gunpowder"],
"Blizzard Cannon" :  ["Hand Cannon", "Glacial Ice"],
"EB-M17A1" :  ["PSR-1", "Hand Cannon"],
"PSR-1" :  ["ZUG", "Sniping Scope"],
"ZUG" :  ["IM-10", "Laser Pointer"],
"IM-10" :  [],
"Sniping Scope" :  ["Binoculars", "Laser Pointer"],
"Binoculars" : ["Bamboo", "Glass Marble"],
"Uranium Cannon" :  ["Hand Cannon", "Arcane Stone"],
"Elegance" :  ["C5", "SAM57"],
"C5" :  ["V-PP", "Steel"],
"V-PP" :  [],
"SAM57" :  ["F92S", "Steel"],
"F92S" :  [],
"Polaris" :  ["Railgun", "Cell Phone"],
"Railgun" : ["ZUG", "Electronic Parts"],
"Cell Phone" :  ["Blueprint", "Electronic Parts"],
"Devil's Marksman" :  ["Double Revolver SP", "Hand Cannon"],
"Double Revolver SP" :  ["Northern Revolver", "Southern Revolver"],
"Northern Revolver" :  [],
"Southern Revolver" :  [],
"Gatling Gun" :  ["Machine Gun", "AKR98"],
"Machine Gun" :  ["MR16", "Motor"],
"MR16" : ["V-PP", "Laser Pointer"],
"AKR98" :  ["Long Rifle", "Scrap Metal"],
"Long Rifle" :  ["Bamboo", "Gunpowder"],
"Plasma Rifle" :  ["Electron Blaster", "GI-F2"],
"Electron Blaster" :  ["CRT", "Ion Battery"],
"CRT" : ["TV", "Hammer"],
"GI-F2" :  ["Sniping Scope", "AKR98"],
"Golden Rifle" :  ["Bolt Action Rifle", "Gold"],
"Bolt Action Rifle" :  ["Long Rifle", "Steel Pipe"],
"Harpoon Gun" :  ["Long Rifle", "Harpoon"],
"Magnum-Anaconda" :  ["Magnum-Python", "Holy Water"],
"Holy Water" :  ["Water", "Holy Grail"],
"OP5" : ["SAM57", "Laser Pointer"],
"Crude Gun" :  [],
"Sharanga" : ["Engineered Arcane Motor", "Short Crossbow"],
"Short Crossbow" :  [],
"Bow of Apollo" :  ["Steel Bow", "Arcane Stone"],
"Steel Bow" :  ["Long Crossbow", "Iron Sheet"],
"Long Crossbow" :  ["Short Crossbow", "Piano Wire"],
"Piano Wire" :  [],
"Short Crossbow" :  [],
"Bow of Zephyrus" :  ["Composite Bow", "Powder of Life"],
"Composite Bow" :  ["Bow", "Piano Wire"],
"Bow" : [],
"Failnaught" : ["Longbow", "Holy Blood"],
"Longbow" : ["Yumi Bow", "Rubber"],
"Yumi Bow" :  [],
"Elemental Bow" :  ["Scorchbow", "Mighty Bow"],
"Scorchbow" : ["Yumi Bow", "Flint"],
"Mighty Bow" :  ["Wooden Bow", "Gunpowder"],
"Wooden Bow" :  ["Branch", "Piano Wire"],
"Ballista" : ["Steel Bow", "Short Spear"],
"Twinbow" : ["Long Crossbow", "Strong Bow"],
"Strong Bow" :  ["Longbow", "Oil"],
"Cupid's Bow" :  ["Composite Bow", "Crimson Bracelet"],
"Crimson Bracelet" :  ["Ruby", "Bracelet"],
"Bracelet" : [],
"Stallion Bow" :  ["Wooden Bow", "Stallion Medal"],
"Hwacha" : ["Scorchbow", "Power Crossbow"],
"Power Crossbow" :  ["Crossbow", "Rubber"],
"Crossbow" : ["Composite Bow", "Bamboo"],
"Golden-Ratio Bow" :  ["Pellet Bow", "Gold"],
"Pellet Bow" :  ["Branch", "Wire"],
"Sniper Bow" :  ["Long Crossbow", "Laser Pointer"],
"Sniper Crossbow" :  ["Laser Pointer", "Heavy Crossbow"],
"Heavy Crossbow" :  [],
"Crude Bow" :  [],
"Chimera's Cry" :  ["Knuckle", "Engineered Arcane Motor"],
"Phoenix Arms Tattoo" :  ["Gauntlet", "True Samadhi Fire"],
"Gauntlet" : ["Cotton Work Glove", "Steel"],
"Imperial Silk Glove" :  ["Sap Glove", "Mithril String"],
"Sap Glove" :  ["Leather Glove", "Iron Ore"],
"Leather Glove" :  ["Cotton Work Glove", "Leather"],
"Mithril String" :  ["Wire", "Mithril"],
"Frost Petal Hand" :  ["Leather Glove", "Glacial Ice"],
"Power Fist" :  ["Bone Gauntlet", "Ogre Skin"],
"Bone Gauntlet" :  ["Gauntlet", "Turtle Shell"],
"Turtle Shell" :  [],
"Fenrir's Claw" :  ["Iron Claw", "Adamantium"],
"Iron Claw" :  ["Iron Ore", "Claw"],
"Claw" : [],
"Brasil Gauntlet" :  ["Enhanced Gauntlet", "Oilcloth"],
"Enhanced Gauntlet" :  ["Sap Glove", "Gauntlet"],
"RuLai's Palm" :  ["Nirvana Gauntlet", "Buddhist Scripture"],
"Nirvana Gauntlet" :  ["Open Finger Glove", "Ash"],
"Open Finger Glove" :  ["Leather Glove", "Scissors"],
"Ahriman's Hand" :  ["Devil's Hand", "Motor"],
"Devil's Hand" :  ["Iron Claw", "Scissors"],
"One-inch Punch" :  ["Enhanced Gauntlet", "Anatomy Model"],
"White Claw Punch" :  ["Blood Temple Claw", "White Powder"],
"Blood Temple Claw" :  ["Ripped Scroll - 1", "Ripped Scroll - 2"],
"Bloodwing Knuckle" :  ["Wing Knuckle", "Ruby"],
"Wing Knuckle" :  ["Iron Knuckle", "Feather"],
"Iron Knuckle" :  ["Iron Ore", "Knuckle"],
"Meteor Gauntlet" :  ["Gauntlet", "Meteorite"],
"Shatter Shell Gauntlet" :  ["Bone Gauntlet", "Gunpowder"],
"Poison Glass Knuckle" :  ["Glass Knuckle", "Poison"],
"Glass Knuckle" :  ["Knuckle", "Glass Pieces"],
"Crimson Gauntlet" :  ["Gauntlet", "Ruby"],
"Holy Gauntlet" :  ["Sap Glove", "Cross"],
"Lace Glove" :  ["Cotton Work Glove", "Cloth"],
"Dress" : ["Doctor's Gown", "Cloth"],
"Doctor's Gown" :  [],
"Finger Punch" :  ["Open Finger Glove", "Iron Ore"],
"Rubber Glove" :  ["Cotton Work Glove", "Rubber"],
"Crude Glove" :  [],
"Remote Mine" :  ["Engineered Arcane Motor", "RDX"],
"Double Guillotine" :  ["Jungle Guillotine", "Pendulum Axe"],
"Jungle Guillotine" :  ["Booby Trap", "Shamshir"],
"Booby Trap" :  ["Snare", "Glue"],
"Snare" : [],
"Pendulum Axe" :  ["Bamboo Trap", "Axe Chain"],
"Bamboo Trap" :  ["Snare", "Bamboo"],
"Smart Bomb" :  ["RDX", "Cell Phone"],
"Claymore" : ["Small Claymore", "Iron Ball"],
"Small Claymore" :  ["Glass Pieces", "Mine"],
"Hidden Maiden" :  ["Stingburst", "Meiji's Roulette"],
"Meiji's Roulette" :  ["Bamboo", "Kitchen Knife"],
"C-4" :  ["RDX", "White Powder"],
"Fire Trap" :  ["Explosive Trap", "Oilcloth"],
"Explosive Trap" :  ["Booby Trap", "Gunpowder"],
"Fire Mine" :  ["Mine", "Oilcloth"],
"Electrical Shock Trap" :  ["Dead Battery", "Piano Wire"],
"Hunting Trap" :  [],
"Tiara of Light" :  ["Crystal Tiara", "Angel's Wing"],
"Crystal Tiara" :  ["Tiara", "Glass Pieces"],
"Tiara" : ["Circlet", "Wire"],
"Circlet" : ["Hairband", "Branch"],
"Hairband" : [],
"Angel's Wing" :  ["Bishop's Cassock", "Feather"],
"Bishop's Cassock" :  ["Cross", "Cassock"],
"Cassock" : [],
"Imperial Crown" :  ["Crown", "Crimson Bracelet"],
"Crown" :  ["Gold", "Ruby"],
"Tactical OPS Helmet" :  ["Ballistic Helmet", "Cell Phone"],
"Ballistic Helmet" :  ["Bike Helmet", "Bullets"],
"Bike Helmet" :  [],
"Bullets" : [],
"Imperial Burgonet" :  ["Close Helm", "Gold"],
"Close Helm" :  ["Steel Chain", "Mask"],
"Mask" : ["Glasses", "Feather"],
"Glasses" : [],
"Mithril Helm" :  ["Close Helm", "Mithril"],
"Helm of Banneret" :  ["Close Helm", "Gold"],
"Laurel Wreath" :  ["Circlet", "Tree of Life"],
"Prophet's Turban" :  ["Scarf", "Holy Water"],
"Motorcycle Helmet" :  [],
"Safety Helmet" :  ["Bike Helmet", "Stone"],
"Beret" :  ["Fabric Armor", "Scissors"],
"Fabric Armor" :  [],
"Fire Helmet" :  ["Bike Helmet", "Water"],
"Hiking Hat" :  [],
"Queen of Hearts" :  ["Arcane Stone", "Playing Cards"],
"Guardian Suit" :  ["Sheet Metal Armor", "Engineered Arcane Motor"],
"Sheet Metal Armor" :  ["Fabric Armor", "Steel"],
"Hellrider's Jacket" :  ["Rider Jacket", "True Samadhi Fire"],
"Rider Jacket" :  ["Leather Jacket", "Steel Chain"],
"Leather Jacket" :  ["Windbreaker", "Leather"],
"Windbreaker" : [],
"Passionate Dress" :  ["Dress", "True Samadhi Fire"],
"Mithril Armor" :  ["Chain Armor", "Mithril"],
"Chain Armor" :  ["Leather Armor", "Steel Chain"],
"Leather Armor" :  ["Fabric Armor", "Leather"],
"Commander's Armor" :  ["Chain Armor", "Gold"],
"Kabana" : ["Sheet Metal Armor", "Adamantium"],
"Covert Agent Uniform" :  ["Hanbok", "Purified Water"],
"Hanbok" : ["Dress", "Flower"],
"Flower" : [],
"Dazzling Armor" :  ["Hanbok", "Purified Water"],
"Battle Suit" :  ["Bulletproof Vest", "Diving Suit"],
"Bulletproof Vest" :  ["Military Suit", "Iron Sheet"],
"Military Suit" :  ["Windbreaker", "Branch"],
"Diving Suit" :  ["Full Body Swimsuit", "Rubber"],
"Full Body Swimsuit" :  [],
"Blood Red Hood" :  ["Patched Robe", "Holy Blood"],
"Patched Robe" :  ["Monk's Robe", "Cloth"],
"Monk's Robe" :  [],
"Rocker's Jacket" :  ["Rider Jacket", "Iron Sheet"],
"Clergy's Cassock" :  ["Bishop's Cassock", "Gold"],
"Chang Pao" :  ["Qipao", "Herbal Liquor"],
"Qipao" : ["Dress", "Scissors"],
"Dress Shirt" :  ["Cloth", "Scissors"],
"EOD Suit" :  ["Bulletproof Vest", "Patched Robe"],
"Dragon Dobok" :  ["Qipao", "Herbal Liquor"],
"Crusader Armor" :  ["Sheet Metal Armor", "Bishop's Cassock"],
"Amazoness Armor" :  ["Sheet Metal Armor", "Bikini"],
"Bikini" : ["Full Body Swimsuit", "Scissors"],
"Optical Camouflage Suit" :  ["Diving Suit", "Glass Panel"],
"Glass Panel" :  ["Glass Pieces", "Glue"],
"Tuxedo" :  ["Suit", "Lace Glove"],
"Suit" :  ["Dress Shirt", "Cloth"],
"Butler's Suit" :  ["Suit", "Lace Glove"],
"Sunset Armor" :  ["Sheet Metal Armor", "Ruby"],
"Bunker Jacket" :  [],
"Splendor" :  ["Creed of the Knight", "Electron Blaster"],
"Creed of the Knight" :  ["Steel Shield", "Squad Leader Armband"],
"Steel Shield" :  ["Leather Shield", "Steel"],
"Leather Shield" :  ["Turtle Shell", "Leather"],
"Squad Leader Armband" :  ["Reserve Armband", "Needle"],
"Reserve Armband" :  [],
"Radar" :  ["Vital Sign Sensor", "Blueprint"],
"Vital Sign Sensor" :  [],
"Bracelet of Skadi" :  ["Glacial Ice", "Bracelet"],
"Cosmic Watch" :  ["Cell Phone", "Watch"],
"Watch" : [],
"Draupnir" : ["Golden Bracelet", "Wrist Band"],
"Golden Bracelet" :  ["Gold", "Bracelet"],
"Wrist Band" :  ["Rubber", "Bandage"],
"Bandage" : [],
"Mithril Shield" :  ["Turtle Shell", "Mithril"],
"Sword Stopper" :  ["Bazuband", "Iron Claw"],
"Bazuband" : ["Arm Warmers", "Iron Sheet"],
"Atlas Gauntlet" :  ["Gauntlet", "Ogre Skin"],
"Sword of Shah Jahan" :  ["Golden Bracelet", "Sheath"],
"Sheath" :  ["Iron Sheet", "Leather"],
"Bracer" :  ["Arm Warmers", "Relief Patch"],
"Relief Patch" :  [],
"Thimble" : [],
"Boots of Hermes" :  ["Feather Boots", "Arcane Stone"],
"Feather Boots" :  ["Feather", "Boots"],
"Boots" : [],
"EOD Boots" :  ["Steel Knee Pads", "Advanced Military Boots"],
"Steel Knee Pads" :  ["Steel", "Knee Pads"],
"Knee Pads" :  ["Leather", "Cloth"],
"Advanced Military Boots" :  ["Boots", "Cloth"],
"Mithril Boots" :  ["Feather Boots", "Mithril"],
"Killer Heels" :  ["High Heels", "Glass Pieces"],
"High Heels" :  ["Slippers", "Scrap Metal"],
"Slippers" : [],
"Maverick Runner" :  ["Heelys", "Electronic Parts"],
"Heelys" :  ["Running Shoes", "Iron Ball"],
"Running Shoes" :  [],
"Battle Boots" :  ["Advanced Military Boots", "Knee Pads"],
"Chain Leggings" :  ["Tights", "Steel Chain"],
"Tights" : [],
"Hiking Shoes" :  [],
"Wooden Shoes" :  [],
"Kundala" : ["Moon Stone", "Adamantium"],
"Veritas Lux Mea" :  ["Saint's Relic", "Buddha Sarira"],
"Saint's Relic" :  ["Cross", "Holy Grail"],
"Buddha Sarira" :  ["Wooden Fish", "Buddhist Scripture"],
"Schrodinger's Box" :  ["Poison", "Box"],
"Box" : [],
"Pirate Flag" :  ["Flag", "Twin Sword"],
"Flag" :  ["Flag Pole", "Cloth"],
"Sultan's Quiver" :  ["Mounted Archer's Quiver", "Gold"],
"Mounted Archer's Quiver" :  ["Quiver", "Belt"],
"Belt" :  ["Leather", "Scrap Metal"],
"Quiver" :  ["Leather", "Bamboo"],
"Quiver of Infinity" :  ["Quiver", "Mirror Marble"],
"Mirror Marble" :  ["Glass Marble", "Mithril"],
"Uchiwa" : ["Doll", "Fan"],
"Doll" : ["Glass Marble", "Cloth"],
"Dice of Destiny" :  ["Dice", "Playing Cards"],
"Magazine" :  ["Iron Sheet", "Box"],
"Crimson Flower" :  ["Powder of Life", "Flower"],
"Bull Intestine" :  [],
"Grilled Tuna" :  ["Tuna", "Heated Whetstone"],
"Tuna" : [],
"Braised Potato" :  ["Potato", "Soy Sauce"],
"Potato" : [],
"Soy Sauce" :  [],
"Ten Tonics Soup" :  ["Turtle Soup", "Scrolls of DongYi"],
"Turtle Soup" :  ["Turtle Shell", "Cooking Pot"],
"Garlic Ramen" :  ["Hot Ramen", "Garlic"],
"Garlic" : [],
"Hot Ramen" :  ["Ramen", "Boiling Water"],
"Ramen" : [],
"Braised Burdock" :  ["Burdock", "Soy Sauce"],
"Burdock" : [],
"Baked Potato" :  ["Potato", "Heated Whetstone"],
"Glazed Sweet Potato" :  ["Sweet Potato", "Honey"],
"Sweet Potato" :  [],
"Honey" : [],
"Grilled Saury" :  ["Saury", "Heated Whetstone"],
"Saury" : [],
"Tuna Can" :  ["Tuna", "Can"],
"Baked Carp" :  ["Carp", "Heated Whetstone"],
"Mocha Bread" :  ["Coffee Liqueur", "Bread"],
"Coffee Liqueur" :  ["Alcohol", "Coffee"],
"Coffee" : [],
"Alcohol" : [],
"Bread" : [],
"Chocolate Chip Cookies" :  ["Chocolate", "Cookie"],
"Chocolate" : [],
"Cookie" : [],
"Baked Sweet Potato" :  ["Sweet Potato", "Heated Whetstone"],
"Chocolate Pie Box" :  ["Chocolate Pie", "Box"],
"Chocolate Pie" :  ["Chocolate", "Bread"],
"Fish Stew" :  ["Carp", "Cooking Pot"],
"Healing Potion" :  ["Herb", "Glass Bottle"],
"Herb" :  ["Oriental Grass", "Flower"],
"Oriental Grass" :  [],
"Fried Chicken" :  ["Bird Meat", "Heated Oil"],
"Bird Meat" :  [],
"Spicy Noodle" :  ["Ramen", "Soy Sauce"],
"Baked Mudfish" :  ["Mudfish", "Heated Whetstone"],
"Mudfish Soup" :  ["Mudfish", "Cooking Pot"],
"Sashimi" :  ["Tuna", "Sharp Kitchen Knife"],
"Stir Fried Ramen" :  ["Ramen", "Frying Pan"],
"Pickled Garlic" :  ["Garlic", "Soy Sauce"],
"Liquor Bread" :  ["Soju", "Bread"],
"Soju" : ["Water", "Alcohol"],
"Garlic Bread" :  ["Garlic", "Bread"],
"French Fries" :  ["Potato", "Heated Oil"],
"Grilled Eel" :  [],
"Herb Medicine" :  ["Turtle Shell", "Scrolls of DongYi"],
"Fresh Sashimi" :  [],
"Gimbap" : [],
"Fried Egg" :  ["Bird Egg", "Heated Oil"],
"Bird Egg" :  [],
"First Aid Kit" :  ["Box", "Pill"],
"Pill" :  ["Scrolls of DongYi", "Oriental Grass"],
"Acupuncture" :  ["Needle", "Scrolls of DongYi"],
"Bungeoppang" :  ["Carp", "Bread"],
"Honey Medicine" :  ["Honey", "Pill"],
"Scorched Rice Soup" :  [],
"Curry" :  ["Curry Powder", "Boiling Water"],
"Curry Powder" :  [],
"Oriental Concoction" :  ["Oriental Grass", "Boiling Water"],
"Scrambled Egg" :  ["Bird Egg", "Frying Pan"],
"Antiseptic" : [],
"Band-Aid" :  [],
"Orange" : [],
"Smelt" : [],
"Relief Patch" :  [],
"Cocktail" :  ["Orange", "Whiskey"],
"Whiskey" : [],
"Cigarettes" :  ["Tobacco Leaves", "Lighter"],
"Tobacco Leaves" :  [],
"Flower Liquor" :  ["Sorghum Wine", "Flower"],
"Sorghum Wine" :  ["Alcohol", "Lighter"],
"Ice Coffee" :  ["Ice", "Coffee"],
"Hot Chocolate" :  ["Chocolate", "Boiling Water"],
"Americano" :  ["Coffee", "Boiling Water"],
"Orangeade" :  ["Orange", "Carbonated Water"],
"Carbonated Water" :  [],
"Burdock Tea" :  ["Burdock", "Boiling Water"],
"Hot Honey Water" :  ["Honey", "Boiling Water"],
"Ionized Soju" :  ["Soju", "Sports Drink"],
"Sparkling Soju" :  ["Soju", "Carbonated Water"],
"Herbal Tea" :  ["Herb", "Boiling Water"],
"Herbal Liquor" :  ["Sorghum Wine", "Oriental Grass"],
"Oriental Raisin Tea" :  ["Branch", "Boiling Water"],
"Honey Water" :  ["Honey", "Water"],
"Half-Filled Glass" :  ["Glass Cup", "Water"],
"Kaoliang Liquor" :  ["Sorghum Wine", "Lighter"],
"1.5L Water Bottle" :  ["Water", "Plastic Bottle"],
"Ice Water" :  ["Ice", "Water"],
"Bacchus" : [],
"Liver Supplement Pill" :  [],
"Silencer" : ["Rubber", "Bamboo"],
"System Shutdown Code" :  ["CD Player", "Blueprint"],
"Wizard's Fishing Pole" :  ["Bamboo", "Piano Wire"],
"Searing Palm Scroll" :  ["Anatomy Model", "Blueprint"],
"Adrenaline Drink" :  ["Bacchus", "Coffee"],
"Clang Clatter" :  ["Plate", "Can"],
"Smoke Bomb" :  ["Flour Bomb", "Gunpowder"],
"Network PC" :  ["Laptop", "Cell Phone"],
"Laptop" : ["Laptop(dead battery)", "Ion Battery"],
"Laptop(dead battery)" :  ["Laptop(faulty circuit)", "Soldering Iron"],
"Laptop(faulty circuit)" :  ["Laptop (broken screen)", "LCD Panel"],
"LCD Panel" :  ["Glass Panel", "CRT"],
"Arrows" : [],
"Crude Silencer" :  [],
"Army Suspenders" :  ["Magazine", "Belt"],
"Optical Camouflage Bag" :  ["Army Suspenders", "LCD Panel"]
}

lmt = 0
for page in pages_var:
	if lmt == limit:
		break
	lmt += 1
	if lmt < startat:
		print("Skipping page %s" % page.name)
	else:
		text = page.text()
		wikitext = mwparserfromhell.parse(text)
		for template in wikitext.filter_templates():
			if template.name.matches('Item Page'):
				items = recipes[page.name]
				items_str = '+'.join(items)
				template.add('recipe',items_str)
		
		newtext = str(wikitext)
		if text != newtext:
			print('Saving page %s...' % page.name)
			page.save(newtext, summary=summary)
		else:
			print('Skipping page %s...' % page.name)