import os

d = {"garena talk talk league": "Talklogo small.png",
"e-sports ranking": "ESR logo small.png",
"reykjavik international games": "Reykjavik International Games Logo Small.png",
"ultraliga": "Ultraliga.PNG",
"gamepolis 2018": "Gamepolis 2018logo.png",
"wellplayed productions": "WPlogo small.png",
"icelandic esports league": "Lenovo Deildinlogo square.png",
"v4 future sports festival": "V4 Future Sportslogo std.png",
"apg premier league": "APG logo small.png",
"mlp legends": "MLP Legendslogo std.png",
"elite challenger series": "ECS logo.png",
"mobafire challenger series": "MCS small.png",
"orléans game show": "Orléans Game Show Logo.png",
"galaxy esports carnival": "GEC logo small.png",
"turkish promotion league": "TPL logo small.png",
"riot games": "Riot Games Logo 2019.png",
"the gathering": "The Gathering Square.png",
"grosbill invitational": "Grosbill Invitational logo small.png",
"red bull strijders": "Red Bull Strijders Dream Team.png",
"europe league championship series 2013": "EULCS 2013 logo small.png",
"finnish esports league": "Finnish Esports Leaguelogo std.png ‎ ",
"north america league championship series 2013": "LCS NorthAmerica Logo.png",
"latin america cup": "Latin Cup logo small.png",
"europe challenger series": "CS EU logo.png",
"2014 international wildcard tournament": "IWC logo small.png",
"gameon": "GameOn Logo Square.png",
"aboekracity championship": "AboekraCity Championship Logo.png",
"north america challenger series": "CS NA logo.png",
"cybergamer": "Cybergamerlogo small.png",
"la grosse ligue": "LGL.png",
"serbian esports league": "Srbija Nacionalna liga.png",
"lan ets": "LAN ETSlogo.png",
"liga portuguesa": "LPLOL 2018 Logo.png",
"copa latinoamérica sur 2015": "CLS logo.png",
"4 nations tournament": "4 Nations Tournament logo.png",
"aaa pro challenge": "aAa Pro Challenge logo.png",
"nations elite esports baltics cup": "NEE Baltics Cup 2017.png",
"montpelier esport show 2017": "MSE.png",
"2015 international wildcard tournament": "IWC logo small.png",
"international wildcard tournament turkey": "IWC Turkey 2015.png",
"xtreme league": "XLG Icon.png",
"all-star 2014 paris": "All-Star Paris 2014 logo small.png",
"colmar esport show": "Colmar Esport Show Logo Small.png",
"fight lol euw": "Fight logo small.png",
"xinhua e-sports conference": "XEC.png",
"oceanic challenger series": "OCS 2018.png",
"black monster cup": "BMCup Small.png",
"esl dutch": "ESL Dutch Championship.png",
"x5 mega arena": "X5 Mega Arena logo small.png",
"longzhu gaming queen invitational": "LongZhu Gaming Queen.png",
"x championship": "XCS logo small.png",
"euw challenger series": "EUW Challenger Series.png",
"x-kom clash": "X-kom-clash-logo.png",
"chile championship series": "Escudoccs.png",
"league of legends championship series": "LCS 2019 Logo Small.png",
"east coast conference": "East Coast Conferencelogo.png",
"wellplayed cup": "Wpclogo small.png",
"island of legends 2014": "IslandofLegends old.png",
"lithuanian esports league": "Lithuanian Esports League Logo.png",
"all-star los angeles 2017": "All-Star 2017 logo.png",
"college east conference": "2018 East Conferencelogo.png",
"cis challenger league": "SLTV CS logo.png",
"world gamemaster tournament": "WGT logo small.png",
"world e-sports masters": "WEMlogo.png",
"vietnam championship series": "VCS logo 2018.png",
"the legends circuit malaysia": "TLC MY logo small.png",
"university esports masters": "University Esports Masters Square.png",
"swiss esports league": "SESL Logo.png",
"sk telecom lte-a lol masters": "Masters logo small.png",
"european masters": "EU Masters logo std.png",
"esl italia championship": "ESL ITA Championship.png",
"wvw national elite cup": "WVW logo small.png",
"worten game ring omen invitational": "Worten Game Ring Omen Invitational.png",
"ign pro league": "Ipllogo small.png",
"garena": "Garena logo small.png",
"la ligue féminine": "La ligue Féminine Logo.png",
"circuit brazilian league of legends": "CBLOL 2017 Logo.png",
"national electronic sports open": "Neso small.png",
"colombia national league": "Colombia National League logo small.png",
"world cyber arena": "WCA logo small.png",
"a1 gaming league": "A1 Gaming League Bulgaria.png",
"women's esports league": "Women%27s Esports League Logo.png",
"invitational italiano 2015": "Invitational Italiano 2015logo small.png",
"we will do it ourselves cup": "WWDIO Cup logo small.png",
"mena championship": "2019 MENA Championship.png",
"esl benelux": "ESL BNL Championship.png",
"ward invitational 2018": "Ward Invitational 2018logo std.png",
"challenger faceoff": "Challenger FaceOff logo small.png",
"thailand grand championship 2014": "Thai GC 2014.png",
"logitech cgpl": "CGPL logo.png",
"fusion.bet championship": "Fusion bet Championshiplogo std.png",
"wichita esports": "Wichita eSportslogo.png",
"vietnam championship series b": "VCSB logo small.png",
"la bruma": "La Bruma Logo Small.png",
"emperor cup": "Emperor Cup 2017 logo.png",
"lol secondary pro league": "LSPL logo Small.png",
"gaming.dk": "Gaming.dk logo.png",
"vietnam championship series a": "VCS Series A Logo.png",
"hong kong esports challenge": "Hkesc logo.png",
"slovenian esports league": "Slovenija Nacionalna liga.png",
"4players.de": "4Players.de logo small.png",
"insomnia": "Insomniaunknown logo.png",
"mountain dew championship series": "Mountain Dew Championship Series logo.png",
"valenciennes game arena": "Valenciennes Game Arena logo.png",
"hitpoint masters": "Hitpoint Masters logo small.png",
"lone star clash 3": "Lone Star Clash 3 logo small.png",
"college north conference": "2018 North Conferencelogo.png",
"circuito nacional argentina": "Circuito Nacional Argentina.png",
"ulol campus series": "ULoL CS logo small.png",
"underdogs": "Underdogs logo small.png",
"copa latinoamérica norte": "CLN logo.png",
"gamergy": "Gamergy Logo Small.png",
"upsurge premier league": "UPL 2019logo.png",
"girlgamer esports festival": "GIRLGAMER 2017 logo.png",
"australian cyber league": "ACL logo small.png",
"big east conference": "Big East Conferencelogo.png",
"mytv telenor lol cup 2016": "MyTV Telenor Cuplogosmall.png",
"riv4l lan tour": "RIV4L Lan Tour Logo.png",
"unilol": "UniLoL 2018 small.png",
"thailand pro league 2015": "ThaiPL logo small 2015.png",
"esl mistrovství čr a slovenska": "ESL Mistrovství Čr a Slovenska.png",
"peach belt conference": "Peach Belt Conferencelogo.png",
"argentine championship series": "SCA logo small.png",
"circuito tormenta": "Circuito Tormenta.png",
"starladder": "Starladder logo small.png",
"twitch rivals": "Twitch Rivals.png",
"pvp.com": "PvPcom logo.png",
"esl proximus": "ESL Proximus Championship.png",
"lenovo legion of champions series iii": "LOC Serie III Logo Square.png",
"metacup series": "Metacup Series Logo.png",
"patch-lan": "Patch-Lan logo.png",
"rift rivals 2018 sea-ljl-opl": "RR P logo small.png",
"solary cup": "SolaryCupLogo.png",
"frag-o-matic": "Frag-o-Matic Logo.png",
"circuito nacional mexico": "Circuito Nacional Mexico.png",
"thailand pro league spring": "TPL Spring logo small.png",
"esl major series": "Emssmalllogo.png",
"lol the champions": "LCK logo small.png",
"turkish challenger series": "TPL logo small.png",
"thailand lcs 2013": "LCS Thai logo.png",
"italian gaming league": "Italian Gaming League Logo.png",
"league of legends european championship": "LEC logo small.png",
"oceanic regional tournament": "OR logo small.png",
"esl championnat national": "ESL France logo small.png",
"the legends circuit singapore": "TLC SG logo small.png",
"world championship": "WCS logo small.png",
"kespa": "KeSPA logo small.png",
"the cloud league": "The Cloud League.png",
"big ten network": "Big Ten Networklogo.png",
"club masters": "ClubMastersLogoSmall.png",
"argentina national league": "Argentina National League logo.png",
"garena premier league": "GPL logo small.png",
"return of the legends": "Return of the Legendslogo square.png",
"granada gaming": "Granada Gaming Square.png",
"nordic championship": "Nordic Championship logo small.png",
"turkey academy league": "TR Academy logo.png",
"lvp división de honor": "LVP DdH Logo.png",
"telenorligaen": "Telenorligaen logo.png",
"thailand pro league": "ThaiPL logo small.png",
"thailand grand championship 2013": "Logo LoL TGC2013.png",
"league of legends nova league": "LNL logo small.png",
"2015 international wildcard invitational": "IWCI 2015 logo.png",
"dreamhack": "DH-star.png",
"leaguecraft ggclassic": "Leaguecraft logo small.png",
"tencent games carnival": "TGC logo small.png",
"croatian esports league": "Hrvatska Nacionalna liga.png",
"lol arab tournament": "LoL Arab Tournament.png",
"tencent games arena": "TGA logo small.png",
"survival open 2018": "Survival Open 2018logo.png",
"circuito nacional colombia": "Circuito Nacional Colombia.png",
"techlabs": "Techlabslogo std.png",
"philippine pro gaming league": "PPGL Logo.png",
"league championship denmark new": "League Championship Denmark logo 2019.png",
"omen by hp trophy": "OmenHP logo small.png",
"corsair vengeance cup": "Corsair Vengeance Cup logo.png",
"sudamerican master league": "Sudamerican Master League.png",
"liga master fibertel": "Liga Master Fibertel Square.png",
"nexus fall league": "Nexus Fall League logo small.png",
"esl balkans league": "EBL logo small.png",
"ueg league": "UEG Leaguelogo std.png",
"pmu challenge": "PMU Challenge logo small.png",
"a1 esports league austria": "A1 eSports League Austria Season 1logo std.png",
"swedish esports league": "Swedish Esports Leaguelogo std.png",
"red bull player one 2019": "Red Bull Player One 2019.png",
"superliga esports 2017": "Superliga eSports 2017 Season.png",
"esl euro series": "EES logo small.png",
"cyber games arena": "CGA small.png",
"summoner's inn league": "Summoners Inn Leaguelogo std.png",
"island of legends 2015": "IslandofLegends old.png",
"lol oceanic championship": "LOC logo small.png",
"esl vodafone championship": "ESL Vodafone Championship.png",
"strike league": "Strike Leaguelogo.png",
"mexico national league": "Mexico National League logo.png",
"starswar": "StarsWar logo.png",
"brazil college league": "Brasil College League Logo.png",
"king of nordic": "King of Nordic logo.png",
"elite challenger series 2016": "ECS 2016 logo small.png",
"elite of europe": "Elite of Europe logo small.png",
"rookie challenge": "Rookie Challenge 2019.png",
"solomid series": "Tsm25.png",
"g-league": "Gleaguelogo small.png",
"open tour france": "OTF logo square.png",
"esl pro series": "Epssmalllogo.png",
"assembly": "Assembly Logo Small.png",
"eswc summer 2017": "ESWC logo small.png",
"acc masters of esports": "ACC Masters of Esports logo small.png",
"esportspedia": "Wiki.png",
"pros play for the philippines": "PPPlogo01.png",
"mittmedia cup": "Mittmedia Cup 2015logo std.png",
"rift rivals 2017 lcl-tcl": "RR G logo small.png",
"lol garuda series": "LGS logo small.png",
"ozone evolution cup": "Ozone Evolution Cup logo small.png",
"liga latinoamérica norte": "LLN.png",
"geek days lille 2017": "Geek Days Lille logo small.png",
"selecter cup 2014": "Selecter Cup 2014 logo.png",
"sea tour": "SEA Tourlogo square.png",
"tenerife lan party": "Tenerife LP logo small.png",
"challenge france": "Challenge France logo small.png",
"scan tournament": "Scanlogo small.png",
"lol continental league": "2017 LCL.png",
"roccat king of the hill": "ROCCAT logo small.png",
"fortuna kup 2018": "Fortuna Kup 2018 logo.png",
"esl swisscom hero league": "Esl ch.png",
"electronic sports china cup": "ESCC logo small.png",
"htc ascension": "HTC Ascension logo small.png",
"mčr v počítačových hrách": "MČR Logo Square.png",
"nacs 2014": "Logo-euwcs.png",
"dreamcup 2019": "Dreamcup 2019logo.png",
"occitan championship series": "Occitan Championship Series logo small.png",
"mlg 2012 fall": "MLG 2012 Fall logo.png",
"rift rivals 2018 lln-cls-cblol": "RR Y logo small.png",
"pg nationals": "PG Nationals logo small 2018.png",
"thailand pro league winter": "TPL WT logo small.png",
"intel extreme masters": "Esltumbnail.png",
"rift rivals 2017 lln-cls-cblol": "RR Y logo small.png",
"division cup": "Division Cup Logo.png",
"lcs pro league thailand": "LCS Thai logo small.png",
"rift rivals 2017 lck-lpl-lms": "RR R logo small.png",
"rift rivals 2017 gpl-ljl-opl": "RR P logo small.png",
"logicool g cup": "Logicool G Cup logo small.png",
"dell invitational cup": "Delllogo small.png",
"benelux premier league": "Benelux Premier Leaguelogo std.png",
"asus rog": "ROGlogo.png",
"rift rivals 2017 na-eu": "RR B logo small.png",
"bosnian esports league": "Bosna i Hercegovina Nacionalna liga.png",
"mobafire king of the union": "Mobafire KTU logo small.png",
"college west conference": "2018 West Conferencelogo.png",
"esl": "ESL logo small.png",
"riot polish championship": "Riot Polish Championship logo small.png",
"riot open": "Riot Open 2017.png",
"rio de la plata cup": "Copa Rio de la Plata 2017.png",
"slice n dice championship": "Slice n Dice Championship.png",
"college league of legends": "College League of Legendslogo.png",
"2016 international wildcard qualifier": "IWC logo small.png",
"gameathlon": "GameAthlonlogo std.png",
"uk masters s3": "UK Masters S3 std.png",
"red bull player one 2014": "Red Bull Player One 2014.png",
"logitech challenge brasil": "LogC BR 2016 Logo.png",
"golden league": "Golden League.png",
"legends cyber arena": "LCA logo.png",
"red bull itemania": "Red Bull Itemania.png",
"empiretv challenge": "EmpireTV Challenge logo small.png",
"red bull factions": "Red Bull Factionslogo small.png",
"razor league": "Razor Leaguelogo std.png",
"iesf 2013 world championship": "IeSF logo small.png",
"gfinity invitational": "Gfinity Small.png",
"ragnarök": "Rag-logo.png",
"esport fest 2016": "Esport Fest 2016logo std.png",
"thailand pro league summer": "TPL Summer logo small.png",
"raidcall": "Raidcall logo small.png",
"torneo nazionale italiano 2016": "Torneo Nazionale Italiano 2016 logo small.png",
"polska liga esportowa": "FE PLE logo.png",
"puchar polski cybersport": "PPC logo small.png",
"leaguepedia": "LPLogoBook25x25.png",
"major league gaming": "MLG-Logo-Small.png",
"danish esports league": "Danish Esports Leaguelogo std.png",
"europe league championship series": "EU LCS logo small.png",
"gamers assembly": "Gamers Assembly logo small.png",
"lyon e-sport": "Lyon e-Sport logo small.png",
"prefire the league": "PTL Logo.png",
"premier tour": "Premier Tour 2018logo std.png",
"brazil gaming league": "BGL logo.png",
"jingdong cup": "Jingdong Cup logo small.png",
"blackpills cup": "Blackpills Cup logo.png",
"kings of the baltics": "Kings of the Baltics Square.png",
"lol japan league challenger series": "LJLCS logo small.png",
"polish open 2019": "Polish Open 2019.png",
"polylan": "PolyLAN Logo Square.png",
"esl brasil": "ESL BRPL Logo.png",
"ozone hero's evolution cup": "Ozone logo small.png",
"player one elite series": "Player One Elite Serieslogo.png",
"la ligue française": "LFL Logo.png",
"e-sports festival 2015": "ESF HK logo small.png",
"división de honor mexico": "División Honor Mexico.png",
"torneo nazionale italiano 2014": "Torneo Nazionale Italiano 2014 logo small.png",
"ovs fest 2016": "OVS Fest logo std.png",
"faceit challenger invitational": "Faceit logo.jpg",
"ogn": "ogn logo.png",
"op network lol": "OP Network LoL.png",
"oceanic pro league": "OPL logo small.png",
"emperor esports stars": "ES logo small.png",
"circus e-sport tour": "Circus E-Sport Tour Logo.png",
"league of legends sea tour": "LST logo small.png",
"eevent": "EEvent Square.png",
"razer lol challenge": "Razer LoL Challenge logo small.png",
"international esports tournament": "IET logo small.png",
"game'her cup": "Game%27Her Cup Logo.png",
"brazil mega cup": "BMC Logo Simple.png",
"nvidia game festival": "NGFlogo small.png",
"norwegian esports league": "Norwegian Esports Leaguelogo std.png",
"uk masters": "UK Masters logo.png",
"netparty fyn": "NetParty Fyn Square.png",
"sltv starseries": "sltv logo small.png",
"epicgear cup": "EpicGear Cup logo small.png",
"challengers korea": "CK logo.png",
"taiwan esports league": "TESLlogo small.png",
"national electronic sports tournament": "NEST logo small.png",
"thor": "Thorlogo small.png",
"all-star las vegas 2018": "All-Star 2018 Logo 2.png",
"inspot": "InSpot logo small.png",
"garena semi-pro league": "Garena SPL logo.png",
"macedonian esports league": "Makedonija Nacionalna liga logo.png",
"greek legends league": "Greek Legends League logo.png",
"lol battle arena": "LBA S1 logo.png",
"nc": "Nc-arena.png",
"esm": "ESM Logo Square.png",
"4gamers": "4Gamers logo.png",
"esl southeast europe championship": "SEEC new version.png",
"north america scouting grounds": "NA Scouting Grounds logo small.png",
"north american challenger league": "Nacl small.png",
"league of origin": "League of Origin.png",
"esl clash of nations": "ESL Clash of Nations.png",
"north america league championship series": "NA LCS logo small.png",
"kings of europe": "Kings of Europe logo small.png",
"nicegametv lol battle": "NLB Logo Small.png",
"copa latinoamérica sur": "2017 CLS logo.png",
"esports balkan league": "EBL Logo.png",
"all-star 2013 shanghai": "All-Star Shanghai 2013 logo small.png",
"brazilian challenger circuit": "CDLOL 2015 logo.png",
"mountain west conference": "Mountain West Conferencelogo.png",
"valor league": "Valor League.png",
"moscow mayor cup 2018": "Moscow Mayor Cup 2018 Logo.png",
"aorus league": "Aorus League.png",
"demacia cup": "Demacia Championship 2018.png",
"circuito nacional chile": "Circuito Nacional Chile.png",
"occitanie esports": "Occitanie Esports logo small.png",
"singapore legends series": "SLS logo small.png",
"infoshow": "Infoshow Logo.png",
"lega seconda": "Lega Secondalogo std.png",
"millenium": "Millenium logo small.png",
"balkan lan masters": "Balkan Lan Masters Mainlogo std.png",
"2015 all-star event": "LoL-AS-LA2015 Small.png",
"esl major las": "ESL Major LAS.png",
"lvp uk league championship": "LVP UKLC logo small.png",
"egaming": "EGaming 2017logo square.png",
"maximus cup 2018": "Maximus cup 2018.png",
"maximus cup 2017": "Maximus cup.png",
"magyar nemzeti e-sport bajnokság": "MNEB logo.png",
"tweakers gaming live": "Tweakers Gaming Live 2018 Logo.png",
"mid-season invitational": "MSI logo.png",
"esl meisterschaft 2nd division": "Esl de.png",
"madrid open cup 2018": "Madrid Open 2018logo.png",
"lol international collegiate championship": "LICC 2016 logo.png",
"the legends circuit": "TLC logo small.png",
"all stars league": "All Stars League.png",
"league one": "L1logosmall25.png",
"lvp segunda division": "LVP SD logo small.png",
"nvidia geforce esports cup": "Nvidia GeForce Esports.png",
"pgl": "PGL logo.png",
"lvp la copa elcorteinglés": "LVP La Copa ElCorteIngléslogo std.png",
"mundo g tournament": "Mundo G logo small.png",
"lvp clasificatorio challenger series": "LVP Challenger Serieslogo std.png",
"sk trophy": "SK Trophy logo small.png",
"lolpro.com curse invitational": "Curse Invitational logo small.png",
"lol championship malaysia": "LCM logo small.png",
"intel": "Intel logo small.png",
"international wildcard tournament chile": "2015 IWC Chile LogoBig.png",
"liga nacional movistar": "Liga Nacional Movistar 2019.png",
"ldlc nashor's trophy": "LDLC logo small.png",
"yousee ligaen": "YouSee Ligaenlogo std.png",
"tyler1 championship series": "Tyler1 Championship Series Logo Small.png",
"the league": "The League.png",
"thailand game show": "Thailand Game Show.png",
"chile national league": "Chile National League logo small.png",
"magyar elit bajnokság": "Magyar Elit Bajnoksag std.png",
"tencent lol pro league": "LPL 2017 logo.png",
"lone star clash 2": "Lone Star Clash 2.png",
"liga tica de leyendas": "Liga Tica de Leyendas.png",
"cyberathlete professional league": "Cplsmalllogo.png",
"landmark conference": "Landmark Conferencelogo.png",
"baltic esports league": "BEL.png",
"lol master series": "LMS 2016 logo.png",
"circuito de leyendas norte": "CDL 2018.png",
"esl mistrzostwa polski": "ESL MP Logo.png",
"lol ladies battle": "LLB logo.png",
"alphadraft challenger league": "ADCL logo small.png",
"insomnia new": "Insomnia63 logo small.png",
"lol japan league": "LJL 2016 logo.png",
"cybersport league": "Liga cybersport.png",
"copenhagen games": "Copenhagengames logo small.png",
"power league gaming": "PLG logo square.png",
"lol continental league open cup": "LCL Open Cuplogo std.png",
"lol champions korea": "LCK logo small.png",
"league of legends greek league": "LGL Logo.png",
"league championship denmark": "LCD logo small.png",
"a1 esports league austria season 2": "A1 eSports League Austria Season 2logo std.png",
"world leisure games": "WLG logo small.png",
"liga latinoamerica": "Liga Latinoamerica logo small.png",
"liga de honor entel": "Liga Honor Entel logo small.png",
"legend series": "Legend Series logo std.png",
"championnat francophone": "CFP logo small.png",
"league university cup": "League University Cup logo small.png",
"in2lol": "In2LOL logo small.png",
"league of legends roadshow": "LoL RoadshowLogo Small.png",
"logitech g challenge": "Logitech2016 square.png",
"china joy": "ChinaJoy logo small.png",
"island of legends": "Island of Legends logo small.png",
"gift the rift": "Gift the Rift logo.png",
"esl nationals česko a slovensko": "ESL Nationals Česko a Slovensko.png",
"king of switzerland": "King of Switzerland 2018.png",
"dailymotion challenger cup": "DMCC.png",
"taiwan regional finals 2015": "2015 Season Taiwan Regional Finals.png",
"lega prima": "Lega Prima logo small.png",
"king of sea": "25px-Kingofsea.png",
"college south conference": "2018 South Conferencelogo.png",
"oserv lol tour": "Oserv-Esportlogo.png",
"baolo championship series": "Baolo Championship Serieslogo std.png",
"world cyber games": "WCGlogo small.png",
"battle of the atlantic": "LCSlogo small.png",
"cca masters of esports": "CCA Masters of eSports 2017.png",
"esl masters spain": "ESL-Masters-Spain-2016.png",
"kayzr league": "Kayzr League Logo.png",
"jcg premier league": "JCG logo small.png",
"montenegrin esports league": "Crna Gora Nacionalna liga.png",
"itplanet e-sports masters": "Itplanet logo small.png",
"pax": "PAX logo small.png",
"lol japan league scouting grounds": "LJL 2019 Scouting Grounds.png",
"liga de videojuegos professional": "LVP logo small.png",
"iem challenger": "IEM Challenger Logo.png",
"international e-culture festival": "Ieflogo small.png",
"iberian cup": "Iberiancup.png",
"thailand lcs": "Thailand LCS Logo.png",
"hyperplay": "Hyperplay 2018logo std.png",
"ligue pcs 2018-2019": "Ligue PCS 2018-2019 Square.png",
"esl meisterschaft": "Esl de.png",
"hong kong esports tournament": "HKES small.png",
"circuito tico de leyendas": "Circuito Tico De Leyendas 2019.png",
"turkish championship league": "TCL 2019 logo small.png",
"superliga abcde": "Superliga ABCDE Logo.png",
"ggla challenger arena": "GGLA logo small.png",
"na academy league": "LCS Academy League 2019.png",
"game'her league": "Game'HerLeagueLogo.png",
"gamegune": "GameGune.png",
"dutch college league": "DCL Small.png",
"gameforce masters": "GameForce Masters 2018 Logo.png",
"glorious arena": "GA Small.png",
"olympic": "Olympic logo small.png",
"dreamcup 2018": "Dreamcup 2018logo square.png",
"bloody invitational gaming league": "Bloody Invitational Gaming Leaguelogo.png",
"gillette xl invitational": "Gillette XL Invitationallogo std.png",
"forge of champions": "Forge of Champions 2018 logo.png",
"esl uk premiership": "ESL UK Premiership 2017 logo small.png",
"pro gaming series": "Pro Gaming Series logo 2016.png",
"asian games 2018": "Asian Games 2018.png",
"brazil mega arena": "BRMA Logo 3.png",
"amd red league": "AMD Red Leaguelogo std.png",
"esports festival": "eSports Festival logo small.png",
"carbon winter invitational 2016": "Carbon Winter Invitational 2016.png",
"the party": "The Party Logo Square.png",
"fantasy expo challenge": "FEC logo small.png",
"league of legends greek championship": "LGClogosmall25.png",
"esl premiership": "ESL UK Premiership 2017 logo small.png",
"riftanalyst cup": "RiftAnalyst Cup 2018logo square.png",
"pivip league of legends championship": "PiviP logo.png",
"besl pro": "BESL Pro Square.png",
"esl vip adria league": "ESL VIP Adria League.png",
"circuito de leyendas sur": "CDLS.png",
"lol development league": "LDLlogo small.png",
"lvp superliga orange": "LVP SLO logo small.png",
"clg premier series": "Cpslogo small.png",
"circuito nacional peru": "Circuito Nacional Peru.png",
"amateur league championship series": "AmateurLCS2.png",
"cross border esport": "Cross Border Esport Logo.png",
"gamescom": "Gamescom2.png",
"cga major league": "CGAML logo.png",
"musimundo gaming week": "MusimundoGamingWeek.png",
"battle of universities": "Red Bull College Cuplogo square.png",}


thisdir = 'League Images'
for fname in os.listdir(thisdir):
